# Generated by Django 5.2.4 on 2025-08-07 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_transaction_user"),
        ("reference", "0002_alter_category_options_alter_status_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Тransaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={
                ("user", "status", "tx_type", "category", "sub_category", "amount")
            },
        ),
    ]
