# Generated by Django 5.2.4 on 2025-08-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ["name"],
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="txtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Transaction Type",
                "verbose_name_plural": "Transaction Types",
            },
        ),
    ]
